name: Update README2
on:
  schedule:
    - cron: "*/12 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    
      steps:
      - uses: actions/checkout@v3
      - uses: readme-workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
